### ISSUE TITLE
Plugin does not work with Electrolama's zig-a-zig-ah!

### ISSUE THREAD

**Issue by Clemens-XXX** [romanlum/LoxBerry-Plugin-Zigbee2Mqtt#20]
The zig-a-zig-ah! Stick by Electrolama is the recommended stick for for zigbee2Mqtt. But it did not work with the actual Loxberry Plugin. It _did_ work successful with version 0.4.0 but **did not work with later versions**. I crashes after some minutes. 

From Logfile:

> info 2021-02-14 19:18:43: Starting Zigbee2MQTT version 1.17.1 (commit #99274c7)
> info 2021-02-14 19:18:43: Starting zigbee-herdsman (0.13.59)
> error 2021-02-14 19:19:55: Error while starting zigbee-herdsman

**Comment by Clemens-XXX** [comment]
Maybe solutions here: https://electrolama.com/projects/zig-a-zig-ah/#zigbee2mqtt or here https://www.zigbee2mqtt.io/information/FAQ.html#help-zigbee2mqtt-fails-to-start

**Comment by Clemens-XXX** [comment]
from log

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.14.8
3 info using node@v12.19.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle zigbee2mqtt@1.17.1~prestart: zigbee2mqtt@1.17.1
6 info lifecycle zigbee2mqtt@1.17.1~start: zigbee2mqtt@1.17.1
7 verbose lifecycle zigbee2mqtt@1.17.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle zigbee2mqtt@1.17.1~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/opt/zigbee2mqtt/node_modules/.bin:/opt/loxberry/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
9 verbose lifecycle zigbee2mqtt@1.17.1~start: CWD: /opt/zigbee2mqtt
10 silly lifecycle zigbee2mqtt@1.17.1~start: Args: [ '-c', 'node index.js' ]
11 silly lifecycle zigbee2mqtt@1.17.1~start: Returned: code: 1  signal: null
12 info lifecycle zigbee2mqtt@1.17.1~start: Failed to exec start script
13 verbose stack Error: zigbee2mqtt@1.17.1 start: `node index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:314:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:314:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid zigbee2mqtt@1.17.1
15 verbose cwd /opt/zigbee2mqtt
16 verbose Linux 4.19.118-v7+
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v12.19.0
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 1
22 error zigbee2mqtt@1.17.1 start: `node index.js`
22 error Exit status 1
23 error Failed at the zigbee2mqtt@1.17.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by Clemens-XXX** [comment]
and if I run in terminal

```
Zigbee2MQTT:info  2021-02-14 20:53:45: Logging to console and directory: 'log' filename: zigbee2mqtt.log
Zigbee2MQTT:info  2021-02-14 20:53:45: Starting Zigbee2MQTT version 1.17.1 (commit #99274c7)
Zigbee2MQTT:info  2021-02-14 20:53:45: Starting zigbee-herdsman (0.13.59)
Zigbee2MQTT:error 2021-02-14 20:54:57: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2021-02-14 20:54:57: Failed to start zigbee
Zigbee2MQTT:error 2021-02-14 20:54:57: Exiting...
Zigbee2MQTT:error 2021-02-14 20:54:57: Error: Coordinator failed to start, probably the panID is already in use, try a different panID or channel
    at /opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/startZnp.js:172:23
    at Generator.throw (<anonymous>)
    at rejected (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/startZnp.js:25:65)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.17.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.17.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /opt/loxberry/.npm/_logs/2021-02-14T19_54_57_793Z-debug.log

```

**Comment by Clemens-XXX** [comment]
if i add a pan_id manually in configuration.yaml I get:

```
> zigbee2mqtt@1.17.1 start /opt/zigbee2mqtt
> node index.js

Zigbee2MQTT:info  2021-02-14 22:29:13: Logging to console and directory: 'log' filename: zigbee2mqtt.log
Zigbee2MQTT:info  2021-02-14 22:29:13: Starting Zigbee2MQTT version 1.17.1 (commit #99274c7)
Zigbee2MQTT:info  2021-02-14 22:29:13: Starting zigbee-herdsman (0.13.59)
Zigbee2MQTT:info  2021-02-14 22:29:17: zigbee-herdsman started
Zigbee2MQTT:info  2021-02-14 22:29:17: Coordinator firmware version: '{"meta":{"maintrel":1,"majorrel":2,"minorrel":7,"product":1,"revision":20210120,"transportrev":2},"type":"zStack3x0"}'
Zigbee2MQTT:info  2021-02-14 22:29:17: Currently 0 devices are joined:
Zigbee2MQTT:warn  2021-02-14 22:29:17: `permit_join` set to  `true` in configuration.yaml.
Zigbee2MQTT:warn  2021-02-14 22:29:17: Allowing new devices to join.
Zigbee2MQTT:warn  2021-02-14 22:29:17: Set `permit_join` to `false` once you joined all devices.
Zigbee2MQTT:info  2021-02-14 22:29:17: Zigbee: allowing new devices to join.
Zigbee2MQTT:info  2021-02-14 22:29:17: Started frontend on port 0.0.0.0:8080
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use 0.0.0.0:8080
    at Server.setupListenHandle [as _listen2] (net.js:1317:16)
    at listenInCluster (net.js:1365:12)
    at doListen (net.js:1502:7)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1344:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '0.0.0.0',
  port: 8080
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.17.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.17.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /opt/loxberry/.npm/_logs/2021-02-14T21_29_18_064Z-debug.log
loxberry@loxberry:/opt/zigbee2mqtt $ 

```

**Comment by romanlum** [comment]
Do you have another service running in port 8080?

**Comment by romanlum** [comment]
This is strange, because i configured the frontend on port 8881 and not 8080
Can you post your configuration.yaml (please * the key)

**Comment by Clemens-XXX** [comment]
Thank you for you fast reply.

No open service running on 8080. 

This is my configuration.yaml

> ---
> homeassistant: false
> advanced:
>   log_directory: log
>   log_file: zigbee2mqtt.log
>   log_output:
>   - console
>   - file
>   network_key:
>   - XX
>   - XX
>   - XX
>   - XX
>   - XX
>   - XX
>   - XX
>   - XX
>   - XX
>   - XX
>   - XX
>   - XX
>   - XX
>   - XX
>   - XX
>   - XX
> experimental:
>   output: json
>   new_api: false
> devices: devices.yaml
> groups: groups.yaml
> mqtt:
>   base_topic: zigbee2mqtt
>   server: mqtt://localhost:1883
>   user: XXXX
>   password: YYYYYY
> serial:
>   port: /dev/ttyUSB0
> permit_join: true
> frontend:
>   port: ~
> ...

I also tried a) with network_key: GENERATE and b) with rtscts: false as given here https://electrolama.com/projects/zig-a-zig-ah/#configuration - but success. In 0.4.0 everything worked fine, without modification of configuration file.

**Comment by romanlum** [comment]
hmm it seems that your config  was not correctly migrated :(
set frontend->port to 8881
set experimental->new_api to true

set panid manually as you did it before (This is nomarlly not needed but maybe you have another coordinator runnig elsewhere ??)

**Comment by Clemens-XXX** [comment]
YES. That's the solution. It runs with Version 0.7.1 and also the UI is now accessible. Thank you! :-) 
Should we document it somewhere, so that other can find it? ...

**Comment by romanlum** [comment]
Perfect :)

I saw that you have already added a comment on the wiki. 
I will add a hint on the wiki page.
